### ISSUE TITLE
ability to send data in an object instead of a text file?

### ISSUE THREAD

**Issue by benjamincarp** [nfantone/highcharts-export-server#1]
I'm working on a project where I will have the data I want to chart in memory and it seems pretty inefficient to write it into a text file just os I can pass that file location to -infile.  Is this something others have brought up before?  

It looks like it could be accomplished with just a few lines in mapCLArguments().  I can code it up and send you a pull request if you're interested.

**Comment by benjamincarp** [comment]
hmm... I guess it isn't as simple as I was first thinking since we are passing the data to another process via the command line.  Sorry, that probably should have occurred to me before writing this issue. I guess I'll just write temp files to pass the data in.

**Comment by nfantone** [comment]
@benjamincarp You can use the HTTP interface to generate the chart. Would that be useful to you?

**Comment by benjamincarp** [comment]
That's probably the way I should go.  I was having some trouble getting that to work when I tried last week but I'll give it another go.  Thanks.

**Comment by nfantone** [comment]
Should be as simple as `highcharts-phantomjs start` to fire up the server. Then, just `POST` a json payload with an `"inline"` attribute and set there whatever you were trying to flush to a temp file.
